### ISSUE TITLE
log IRC channel

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#12]
We have an IRC channel! Did you know we have an IRC channel? We have an IRC channel. :-)

We're at ircs://chat.freenode.net:6697/#openorgambassadors.

Let's log it so we can refer back to conversations we have there!

I've had a good experience https://botbot.me/ in the past.

Looks like it would need to a channel operator who [sets this up](https://botbot.me/request/). @semioticrobotic?

**Comment by whit537** [comment]
We should also link to the channel and logs from somewhere like the readme.

**Comment by semioticrobotic** [comment]
Good call, @whit537. I will look at these materials today. At the very least, I can make sure we highlight the channel more prominently here.

**Comment by semioticrobotic** [comment]
I made the IRC channel our "location" designation on the group's home page. As for logging: That's something the ambassadors should definitely discuss.

**Comment by pdurbin** [comment]
Any news on setting up IRC logging? I also like botbot but here's a list of options:

- http://botbot.me
- http://irclog.perlgeek.de
- http://colabti.org/irclogger/irclogger_logs
- http://irclogger.com
- http://logs.glob.uno
- http://echelog.com
- http://transcripts.jboss.org/channel/irc.freenode.org/
- http://irclogs.ubuntu.com
- https://javabot.evanchooly.com
- http://irclogs.jackgrigg.com/irc.freenode.net/
- http://irclogs.shortcircuit.net.au
- http://psha.org.ru/irc/
- http://tunes.org/~nef/logs/
- http://irclog.greptilian.com

**Comment by semioticrobotic** [comment]
Thanks, @pdurbin. This has been on my list of items to raise with the ambassadors—but we've always run out of time at meetings, and the conversation here never gathered sufficient steam. I'm glad you rekindled it. Channel logging is something about which I'd want the community to weigh in; I'm reluctant to simply flip that switch without input.

**Comment by pdurbin** [comment]
Sure, and a link to the channel logs would absolutely need to be put in the topic. Does the community weigh in by commenting here? I'd be happy to hear more about the process for making decisions like this.

**Comment by semioticrobotic** [comment]
Agreed, @pdurbin. And yes, you are welcome to outline a proposal here, as well as on the community mailing list, <openorg-list@redhat.com>. I can be sure you're added to that list, if you'd like.

**Comment by pdurbin** [comment]
The archives of the [openorg-list](https://www.redhat.com/mailman/listinfo/openorg-list) aren't public so for greater transparency, let's just discuss here.

There's not much to outline, really. Logging IRC channels increases transparency so I'm glad this issue is open and I propose that we use https://botbot.me because it's popular and works well.

**Comment by semioticrobotic** [comment]
Thanks, @pdurbin. I'm also in favor of BotBot,me, as @lincolnloop is a friend of the community. Full disclosure: I have never set something like this up, but I'm sure that I can handle it with the group's help.

I will start a thread about this on the community mailing list, too (pointing people here), just to determine whether anyone objects to logging the channel.

**Comment by ipmb** [comment]
I can get the channel setup at botbot.me, just let me know. We have a privacy policy that lets people opt out of having their messages logged if that's a concern https://botbot.me/privacy/

**Comment by semioticrobotic** [comment]
Thanks so much, @ipmb! Having heard no objections in this thread—and none on a separate community email thread dedicated to this issue—I'm going to go ahead and ask for your help with setting this up.

**Comment by ipmb** [comment]
All set! https://botbot.me/freenode/openorgambassadors/

**Comment by semioticrobotic** [comment]
Thanks so much, @ipmb. Looks great. We really appreciate the quick assist.

**Comment by semioticrobotic** [comment]
The IRC channel is [now being logged](https://botbot.me/freenode/openorgambassadors/).
