### ISSUE TITLE
Update my photo plz?

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#15]
Hey @semioticrobotic @jhibbets, any chance we could update my photo/bio on the "[Meet the Ambassadors](https://opensource.com/open-organization/resources/meet-ambassadors)" page? I just linked to that from https://whit537.org/ and realized it's out of date! Can we use what I have on [my bio](https://opensource.com/users/whit537)?

**Comment by semioticrobotic** [comment]
How does that work for you, @whit537?

**Comment by whit537** [comment]
Wunderbar! Thank you, @semioticrobotic! 💃
