### ISSUE TITLE
publish something about delegation

### ISSUE THREAD

**Issue by chadwhitacre** [open-organization-ambassadors/ambassador-board-room#16]
We chatted for a bit on today's (private) ambassador call about this topic. Open source is optimized for people who are naturally comfortable with taking charge and setting their own direction. But many folks in the world respond better to situations where there are clear guidelines about how to contribute in an organization. How can open organizations accommodate this tendency, and help people take more responsibility as they're comfortable doing so?

Some stream of consciousness bullet points culled from @LauraHilliger @ruhbehka @LappleApple et al.:

- list what needs to be done
- provide people with an ability to think for themselves in different places
- framing: "Hey, if this doesn't work for you, try your own thing!"
- mix up task scopes—design some tasks to be really simple
- thank people, communicate where their contribution is utilized, "because you did this, this happened"
- carve out roles for people to fill

**Comment by semioticrobotic** [comment]
Reviewing this once again and wondering if @samuelknuth might have thoughts on it.

**Comment by samuelknuth** [comment]
Yeah this is one of my favorite topics. Delegation is part of this, but this is also talking about taking ownership without formal delegation, which I think is a key to success in a lot of companies these days. I have published a few things on this topic already, but I do like to continually explore through different angles

**Comment by arob98** [comment]
I can draft an article on delegation. Maybe Sam and I can work on it together?

**Comment by semioticrobotic** [comment]
Love it (and love the working notes you sent). Thanks for taking on this important topic, @arob98! Your perspective here will be most valuable.

**Comment by semioticrobotic** [comment]
Thanks, @arob98, for graciously agreeing to help us get this out by June 26!

**Comment by semioticrobotic** [comment]
This is now under final review with @arob98, who did a fantastic job with it.

**Comment by semioticrobotic** [comment]
Now scheduled to appear July 17!

**Comment by semioticrobotic** [comment]
Great work, @arob98!

**Comment by semioticrobotic** [comment]
Haven't seen that flamenco emoji in way too long. Hope you are well, @chadwhitacre, and many thanks for getting us rolling on a great article idea! Didn't @arob98 really knock it out of the park?

**Comment by chadwhitacre** [comment]
Yeah absolutely! I especially like the focus on "shared responsibility" and the super-practical checklist in the conclusion. 👏 @arob98
