### ISSUE TITLE
publish something about "inner circling"

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#17]
- [**Working Draft**](https://docs.google.com/document/d/1GGWsTCJPDC64zs9rgGkrv8JgcfbSnTkIFgFH29LyMtM/edit?usp=sharing)
- [Draft 3](https://docs.google.com/document/d/1Wgee_g98viGvLC2f3xRIvh-v2SeAOuRv8oB-hZgisII/edit?usp=sharing)
- [Draft 2](https://docs.google.com/document/d/1m15aNhOJhpdx-T3iiaDDb1icJUgvlT4TploImq27jsU/edit?usp=sharing)
- [Draft 1](https://docs.google.com/document/d/1kfjod6dvLnKwbihk0N9uBlYBhE9rM6JLprVQOOlNN2E/edit?usp=sharing)

------------------------

Copying over a braindump (of mine) from the [Changelog slack](https://changelog.com/community) re: https://github.com/moby/moby/pull/32691:

> Also about branding: https://opensource.com/business/16/2/how-choose-right-brand-architecture-your-open-source-project.
> But announcing a change like this without any apparent community involvement in the decision itself is a definite recipe for push-back.
> On the other hand, name choice is the ultimate bikeshed, so maybe they wanted to avoid that.
> Our most epic bikesheds w/ Gittip/Gratipay were around renaming. :slightly_smiling_face:
> https://github.com/gratipay/gratipay.com/issues/138
> And then https://github.com/gratipay/inside.gratipay.com/issues/73.
> If renaming a small project like Gittip/Gratipay generated that much engagement, imagine the bikeshed Docker would’ve had on their hands if they’d involved the community in the naming decision! 😮
> Of course, it’d still have been preferable to be honest and transparent about that.
>> Docker is transitioning all of its open source collaborations to the Moby project going forward.
>
> No reasoning given, no explanation. No links to sources. 😞
> It’s like the flip side of inner sourcing: when open source projects have opaque inner circles making decisions behind closed doors.
> Needs a clever name. 😉
> “outer sourcing”
> “inner circling”

**Comment by whit537** [comment]
I've also seen this tendency recently with the Sustain conference, where we have a private weekly call with an inner circle of organizers. It takes work to resist!

And of course our own experience with the ambassadors is relevant as well.

**Comment by whit537** [comment]
"Docker and the 'inner circling' of open source"

**Comment by whit537** [comment]
Okay @semioticrobotic, check this out:

"[Docker, Moby, and 'inner circling' in open source](https://docs.google.com/document/d/1GGWsTCJPDC64zs9rgGkrv8JgcfbSnTkIFgFH29LyMtM/edit?usp=sharing)"

A timely topic, so if you are generally interested in the post, we may want to fast-track it to maximize relevance and readership. Could also work in a few weeks, though it might need mild revision pre-publishing based on any additional developments.

Thoughts?

**Comment by semioticrobotic** [comment]
Just getting caught up, @whit537. Will take a look presently!

**Comment by whit537** [comment]
We have friends. :-)

![screen shot 2017-04-20 at 10 33 50 am](https://cloud.githubusercontent.com/assets/134455/25236052/df2a8c42-25b4-11e7-80f3-f932fb1f0deb.png)

**Comment by whit537** [comment]
@semioticrobotic and I have been communicating in IRC about this (#openorgambassadors on Freenode, unlogged). We've converged on a [draft 3](https://docs.google.com/document/d/1Wgee_g98viGvLC2f3xRIvh-v2SeAOuRv8oB-hZgisII/edit?usp=sharing), and @semioticrobotic is talking with his team about scheduling for publication, possibly as early as next week. The story has hit HackerNews, so the situation is likely to develop further between now and publication. When I started writing, the votes were at 7/110, when I finished my first draft they were at 8/128. Now they are at 29/297 and the ticket title has been changed. We shall see how this unfolds! :-)

**Comment by whit537** [comment]
P.S. Animal friends are likely a combination of Red Hat colleagues invited by @semioticrobotic, as well as some click-through traffic from the Moby announcement PR to here, and maybe a bit of Changelog traffic.

**Comment by whit537** [comment]
Landing at https://opensource.com/open-organization/17/4/avoiding-inner-circling.

**Comment by semioticrobotic** [comment]
Publish date should be tomorrow morning, around 3 a.m. Eastern (give or take a few minutes).

**Comment by whit537** [comment]
We're live! Closing.
