### ISSUE TITLE
publish something about code review

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#18]
Hey @lognaturel, wanna write up a post for OpenSource.com based on the [code review session](https://docs.google.com/document/d/1y0p2V_dkSIFvatEy-mQyoFzipdVwKpILSlt_JFKvpuQ/edit) at CLS? :-)

**Comment by whit537** [comment]
I like your working title in the notes: "Code review: Finding emergent leaders, encouraging everyone to participate." 👍

**Comment by semioticrobotic** [comment]
Would give multiple thumb emojis if I could.

**Comment by whit537** [comment]
The interesting angle here is the connection between the technical side of code review and the cultural side of openness.

**Comment by lognaturel** [comment]
Uhhhh... if you think there's interest, I could do that!

**Comment by semioticrobotic** [comment]
Would love to work with you on a piece, @lognaturel. As @whit537 mentioned, what's most fascinating and pertinent to our readers is the space where the technical and the cultural intersect, as the open organization channel on Opensource.com is really devoted to exploring openness in organizational design/dynamic/culture. Happy to chew on this with you a bit more, if you're interested (I know we are).

**Comment by lognaturel** [comment]
All sounds good to me! I do agree that there are some interesting dynamics at play. One of the big reasons I wanted to discuss these ideas at CLS is that I had a hard time finding meta analysis on the topic. There are lots of projects with interesting approaches and good documentation but it's hard to find out why projects chose their particular approaches, how they evolved them and, as you say, how their processes fit in with the broader project culture. 

I'm pretty swamped for the next month or so but if there's some flexibility in when this would be scheduled to go out, I'm in.

**Comment by semioticrobotic** [comment]
Sure, @lognaturel; we're flexible. Should we circle up in a few weeks and perhaps aim for an early June publication date? I can make a note to get in touch with you about an outline on a future date, if that helps.

**Comment by lognaturel** [comment]
@semioticrobotic I'd rather do early July if we could. I'm traveling a bunch in the next couple of weeks with various deadlines in there. Mid-June would be a good time for me to discuss an outline.

**Comment by semioticrobotic** [comment]
Works for me, @lognaturel. I'll make a note! Very much looking forward to working on this with you over the summer.

**Comment by lognaturel** [comment]
Awesome! Should I share an outline/draft here once I'm ready to get started?

**Comment by semioticrobotic** [comment]
Sure! If you're comfortable with that. Otherwise, you're welcome to email me a file or link.

**Comment by lognaturel** [comment]
@semioticrobotic I haven't forgotten about this, I promise. Just had another good unconference session on a similar topic at OSBridge and an outline is starting to form in my head. The summer of conferences continues but hopefully I can find some time to write things down soon.

**Comment by semioticrobotic** [comment]
Excellent. Looking forward to reading your draft. Thanks, @lognaturel.

**Comment by semioticrobotic** [comment]
How's it going, @lognaturel? How can I be of service?

**Comment by lognaturel** [comment]
Ack, time is going by too quickly, I apologize for continuing to push things back. I'm moving tomorrow and hopefully will find the time after.

**Comment by semioticrobotic** [comment]
we get it, @lognaturel! Have a safe and uneventful move, and we'll touch base when you're settled. Still very much looking forward to working on this with you.

**Comment by lognaturel** [comment]
[Here's](https://docs.google.com/document/d/1EQhU5LlANb5fuCXR_i8bTEtrLFKM5MVkbbTDkVxDQkc/edit) what I have to report so far. Anyone can comment. For some reason I ended up working backwards so you'll see the middle is a lot more developed. If you think the general approach and content can be useful, I /think/ I can have a complete draft by the end of next weekend.

I liked the developing emergent leaders angle and it's something that I will write some about but I found I couldn't build a narrative around it. It's not something I've had a lot of success with myself (but it's still early days in my tenure as a maintainer) and the majority of the folks I have spoken to work on projects on which the bulk of review is done by people who contribute as part of their jobs and/or are the original project creators. I'm sure there are projects for which that's not true but I haven't had a chance to learn much from them yet.

I know the listicle structure is pretty played out. I can move away from that if you think that would be better.

**Comment by semioticrobotic** [comment]
Great, @lognaturel. What I'm seeing so far leads me to believe it's spot on. I left a note I'll reiterate here: The way you've set up the piece—noting that code review may seem like a " technical pursuit best left to the most seasoned contributors to shape and lead, but there’s a big cultural aspect to it"—is the correct approach to take for our audience. The open organization channel at Opensource.com features pieces much more concerned with people, process, and culture (and less with specific technologies and tools). The more you can lean into this angle, the better.

**Comment by lognaturel** [comment]
Hmm, I thought I was writing to other open source developers and maintainers. I generally read from the front page of opensource.com and can't immediately find the channel that you're talking about, can you please link to it? What else should I know about the audience and context? Are they likely to know what code review is and why it's valuable? Why would they want to know about code review?

**Comment by semioticrobotic** [comment]
Sure! Happy to clarify and provide that extra context, @lognaturel.

The [open organization channel](https://opensource.com/open-organization) is the part of Opensource.com most focused on the ways open values and principles affect organizational design and dynamics. Opensource.com's audience is indeed full of developers; the open organization channel more specifically speaks to organizational leaders interested in the ways open principles can help them rethink their approaches to people/process/culture.

We welcome _any_ submission from you. If the piece you're imagining speaks to an audience that's more developer focused, then I'm happy to connect you with the proper editor on our team who can help you make that story as strong as possible. Our goal is simply to bring great open source stories to life—no matter where they fit!

**Comment by semioticrobotic** [comment]
Oh—and to answer your other questions:

- One prospective reader for your article might be the one that's thinking of open sourcing some key component but wants to know how doing so will affect team dynamics, especially during the review process 
- Another prospective reader might know that _open source coding_, as a practice, exists, and wants to learn some tips/strategies for generalizing that manner or style of working to a team that's potentially making something different

**Comment by lognaturel** [comment]
I'm really sorry, I should have asked these key questions about audience before I said yes. I've read through some of the latest articles on the open organization channel and I'm not coming up with a narrative that fits in. I'm still figuring out what works best for the projects that I'm involved in and don't feel like there's a lot I can share with any kind of authority. I don't understand the audience and their needs well enough to make sure I don't lead them astray.

I'd like to contribute to opensource.com at some point but I think this may not be quite the right topic or at least not yet. Basically, what we're talking about here is an article I'd like to read but that I don't think I can write with the experience I have. Apologies for taking so long to reach this disappointing conclusion! As I'm trying to collect my thoughts, I just end up with more questions than answers. It's a topic I'm interested in so perhaps if you don't find anyone to write it first I can propose it again at a later date when I can come up with an outline that makes sense.

**Comment by semioticrobotic** [comment]
No problem, @lognaturel. We understand, and appreciate your honesty here. I'll go ahead and close this thread—but do so entirely in the hope that we'll nevertheless work on something together in the future, when you're ready!
