### ISSUE TITLE
publish something about the Hacker Ethic

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#21]
- [**Working Draft**](https://docs.google.com/document/d/1UOuRbXgXdIh7WLgW4B0gGM7hF4iw5zaOtX6vXc0hDzI/edit)
- [Draft 6](https://docs.google.com/document/d/1VLdEdYQbFnOG9nbgp_mIhoNWScElBcfkkr7vbGThSYI/edit)
- [Draft 5](https://docs.google.com/document/d/1b3qVdCY3C6N_hZ5Na6yI7M1F2CFTZOASIFNWGihzk5o/edit)
- [Draft 4](https://docs.google.com/document/d/1y4mMnmNPnTssDGhEbH5SpFCSMPJppgPhd4rAFjrcDDU/edit)
- [Draft 3](https://docs.google.com/document/d/1-Us96bVkjif8NWuR05THN4y76x0G147h3uPzeqhe4Ks/edit)
- [Draft 2](https://docs.google.com/document/d/14vcWtDWqDHuJzP1NKcYC_kDhH2_By5GE2sapZIPw5Ng/edit)
- [Draft 1](https://docs.google.com/document/d/1_8BY6bg-g-btb8CHVM3fanNAJsvQ5qphXn1ruuxFa-E/edit)

**Comment by whit537** [comment]
Inspired by today's call w/ Jim.

**Comment by semioticrobotic** [comment]
Thanks, @whit537! I'm finishing p some preliminary feedback for you in the document you linked.

**Comment by whit537** [comment]
Got it, thanks. Easy pickins merged in the Google Doc. Wrestling with the more substantive suggestions now ...

**Comment by semioticrobotic** [comment]
Take your time, @whit537, as I will need to return to this tomorrow (probably better anyway, when I'm fresh). Looking forward to it. Shaping up to be great.

**Comment by whit537** [comment]
Fair enough. Feels to me like it needs a rewrite ...

**Comment by semioticrobotic** [comment]
Well, no need to slash and burn. Truly. I think some basic reordering or the paragraphs will make the argument more apparent. I will have another look today and see if I can offer additional suggestions.

**Comment by whit537** [comment]
Thanks @semioticrobotic. I kinda lost myself down the 🐰 :hole: yesterday. Hoping to emerge today. ☺️

**Comment by whit537** [comment]
Okay, @semioticrobotic! Check out [the latest](https://docs.google.com/document/d/1UOuRbXgXdIh7WLgW4B0gGM7hF4iw5zaOtX6vXc0hDzI/edit#). I'm feeling a lot better about it.

**Comment by semioticrobotic** [comment]
Crackerjack, @whit537. Great revisions. Let me get it into production so you can see it in a new context. Thank you!

**Comment by semioticrobotic** [comment]
Have a look!

https://opensource.com/open-organization/17/7/open-org-hacker-ethic

**Comment by whit537** [comment]
Thanks, @semioticrobotic. I took the liberty of making one small change: setting off the quote from Levy as a `blockquote`. Other than that, I'm good to go! 👍

**Comment by whit537** [comment]
We might also change:

> something determined by each individual for themselves

to:

> something each individual determines for themselves

But I'll leave that for you to make if you like.

**Comment by semioticrobotic** [comment]
Agree with the change, and made it. Thanks, @whit537, for the quick review. We'll target next week for publication.

**Comment by whit537** [comment]
Awesome, @semioticrobotic! So glad to have a contribution in the pipeline again! :-)

**Comment by whit537** [comment]
Not sure about the new headline:

> Hiring new talent in a world run by hackers

Is that final?

I believe we started with:

> Organizational identity in an age of global collaboration

**Comment by whit537** [comment]
I guess I'm not seeing where we got "hiring new talent." This piece is more about open ownership than about hiring per se. Can we get back to something more along the lines of "Open ownership and the future of organizations?"

**Comment by semioticrobotic** [comment]
Happy to revert, as it's certainly not final. I was trying to riff on some of the original ideas you'd suggested in the doc, many of which had "hacker" in the title. So I'll go back to Plan A and consult with the team more next week.

**Comment by whit537** [comment]
Thanks @semioticrobotic. I wasn't sure if that was something Jen introduced. I like having "Hacker Ethic" in the subtitle/description, I think it's the right level of tipping people off to what's inside.

**Comment by semioticrobotic** [comment]
A colleague with a keen eye for headlines read (and liked!) your article, @whit537. She offered the following headline/subhead suggestions for tomorrow:

**When the hacker ethic meets old ideas about brand**
The hacker ethic says we should value solving problems more than preserving institutions. But what happens to organizational identity when we do that?

I think we'll give it a whirl and see how readers respond. Looking forward to seeing responses to your great work.

**Comment by whit537** [comment]
Works for me, glad we're live! May I offer you the delight of closing this ticket? ☺️ 🙇

**Comment by semioticrobotic** [comment]
Ha! With relish!
