### ISSUE TITLE
You're open so why are you such a privacy nut?

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#30]
Ambassador @arob98 has begun the first draft of this important piece. @LauraHilliger may want to chime in with her thoughts or motivations for opening this issue.

**Comment by chadwhitacre** [comment]
Love the topic! Safety and consent as prerequisites for transparency and openness was one of the [hard lessons learned](https://opensource.com/open-organization/16/9/openness-means-to-what-end) out of Gratipay. Excited to see where you go with this, @arob98!

**Comment by LauraHilliger** [comment]
@arob98 happy to give you some feedback on this if you post a URL.

**Comment by semioticrobotic** [comment]
Scheduled to publish on January 8 as ["Should open leaders expect to have privacy?"](https://opensource.com/open-organization/18/12/open-leaders-and-privacy-guide)

Awesome jon, @arob98!

**Comment by semioticrobotic** [comment]
Published today! Nice work, @arob98!
