### ISSUE TITLE
"Open" and personality types

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization-ambassadors/ambassador-board-room#31]
- Do "open" contexts and organizations attract a certain "type" of participant?

**Comment by jenkelchner** [comment]
@LauraHilliger would love to contribute of course!!

**Comment by semioticrobotic** [comment]
I'm sure you have this well in hand. Looking forward to the draft!

**Comment by LauraHilliger** [comment]
I was on a roll. @semioticrobotic not finished, but getting long. I don't have a title, am worried that I went somewhere other than where we were thinking we'd go, but there's a lot of linkage to our principles, so I'm feeling quite good about this:

https://docs.google.com/document/d/1ceafGugmBdRnE30UCrLDlktmpDafzSNZkFHl24JtKHw/edit#

**Comment by semioticrobotic** [comment]
Your timing here is amazing (as usual), because @RonMcFarland just sent me a (roughly) 6,000-word, two-part review of _The H Factor_, which addresses themes personality profiles and community engagement. What a great theme to begin rolling out in September. I will have more soon—promise!

**Comment by semioticrobotic** [comment]
I really like what you've done so far, @LauraHilliger. I've made some edits and posed a few questions in the margins.

You'll see that the most significant suggestion I've made is to move your "Mozilla narrative" further up. I think that's the best way to orient Opensource.com readers specifically to the relevance of the subject.

Take a look and see what you think.

**Comment by semioticrobotic** [comment]
New revisions and additions are looking great, @LauraHilliger. It looks like you're working on another section. Happy to re-read when you've got that where you'd like it to be.

**Comment by LauraHilliger** [comment]
added the last section. I lost all my steam though. Does it end too abruptly? I feel like I'm having trouble wrapping it up...

**Comment by semioticrobotic** [comment]
I shall take a look!

**Comment by semioticrobotic** [comment]
I think this is looking great, @LauraHilliger. You'll see in the draft that I asked for your input on just one more thing (I know, I know...), but notwithstanding that I think we're in great shape. Important piece! Thanks for working on it.

**Comment by semioticrobotic** [comment]
Perfect! Done. I'll get it into production and drop you a line. Nice work!

**Comment by semioticrobotic** [comment]
Scheduled to run on Tuesday, November 13 as "Have you seen these personalities in open source?"

Thanks, @LauraHilliger!

**Comment by semioticrobotic** [comment]
Published!
