### ISSUE TITLE
The challenges of decoding open source DNA

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#35]
Proposed article from Jason Hibbets

**Comment by semioticrobotic** [comment]
You still noodling on this, @jhibbets?

**Comment by jhibbets** [comment]
I've been a little distracted lately ;)

Let me look back at your feedback later this week and see if the writing
bug strikes.

Thanks for the reminder here. Long forgotten.

**Comment by semioticrobotic** [comment]
Scheduled to publish on January 29, 2019 as ["The challenges of decoding open source DNA."](https://opensource.com/open-organization/19/1/translating-open-source-dna)

Thanks, @jhibbets!

**Comment by semioticrobotic** [comment]
Published! Great work, @jhibbets!
