### ISSUE TITLE
Rethinking "culture fit"

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#37]
Ambassador @jenkelchner proposed this piece, based on the forthcoming chapter from _The Open Organization Leaders Manual_ 2nd edition.

**Comment by semioticrobotic** [comment]
We're targeting and October 2, 2018 publication date.

**Comment by semioticrobotic** [comment]
Do you think we'll be able to finalize this by September 25 or 26, @jenkelchner?

**Comment by jenkelchner** [comment]
@semioticrobotic - you'll have it today, Sir.

**Comment by jenkelchner** [comment]
@semioticrobotic - done. Ready to roll and change the world. :)

**Comment by semioticrobotic** [comment]
Looking great to me, @jenkelchner. Thanks for knocking another one out so quickly and impressively. I'll get it into production soon.

**Comment by semioticrobotic** [comment]
Officially scheduled for October 9, 2018.

**Comment by semioticrobotic** [comment]
Now published as ["Stop hiring for culture fit: 4 ways to get the talent you want."](https://opensource.com/open-organization/18/10/reconsider-culture-fit) Congratulations, @jenkelchner!
