### ISSUE TITLE
"Empowered" does not mean "unmanaged"

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#38]
Proposed article from ambassador @amatlack.

**Comment by amatlack** [comment]
First draft is ready! I shared it with you @semioticrobotic and also my colleagues working with me on this empowerment stuff so they can flag any potential issues or things I missed.

**Comment by semioticrobotic** [comment]
Looking strong, @amatlack. I made a few changes and posed just a few clarifying (I hope) questions in the margins.

**Comment by amatlack** [comment]
@semioticrobotic I think is better now? Heidi had some good suggestions too I think, sprinkled in some more about how mgmt should shift from directives to guidelines

**Comment by semioticrobotic** [comment]
Crushed it, @amatlack. I'll get it into production. Way to go!

**Comment by semioticrobotic** [comment]
Approved and scheduled to run on October 2, 2018. Great work, @amatlack!

**Comment by semioticrobotic** [comment]
Now live as ["Beyond engagement: What leaders need to know about empowering others."](https://opensource.com/open-organization/18/10/understanding-engagement-empowerment) Congratulations, @amatlack!
