### ISSUE TITLE
Open organizations must embrace remote work

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#42]
Proposed article from @funnelfiasco.

**Comment by semioticrobotic** [comment]
Great draft, @funnelfiasco. You'll see that my edits consist primarily of reshuffling some of your ideas into a slightly different paragraph structure. See what you think of that.

**Comment by funnelfiasco** [comment]
Looks good to me!

**Comment by semioticrobotic** [comment]
Scheduled to published January 22, 2019, as ["Letting people work where they want shows how much you value them."](https://opensource.com/open-organization/19/1/remote-work-inclusivity)

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/19/1/remote-work-inclusivity). Nice work, @funnelfiasco!
