### ISSUE TITLE
Why do open organizations have open secrets?

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#46]
A [recent article in HBR](https://hbr.org/2019/01/why-open-secrets-exist-in-organizations) raises the issue of "open secrets" in organizations, and it asks some questions I think would prompt an interesting response/rejoinder from the open organization community:

> Why do issues remain open secrets in organizations where multiple employees know about a problem or a concern, but no one publicly brings it up? ... We found that as issues become more common knowledge among frontline employees, the willingness of any individual employee to bring those issues to the attention of the top-management _decreased_.

A [full research report](https://journals.aom.org/doi/10.5465/amj.2017.0245) from the authors is also online.

**Comment by LauraHilliger** [comment]
@semioticrobotic  I saw this 42 minutes ago and then I went on a tear: https://docs.google.com/document/d/1lEVxIq9Vv2Npoar3EZqFcBzBb6gY-Kx-y_YiLgbcqUY/edit

**Comment by semioticrobotic** [comment]
Nice! Thanks @LauraHilliger. I will edit in the next day or two and have some feedback in-doc for you. Much appreciated!

**Comment by semioticrobotic** [comment]
I think this is off to a great start, @LauraHilliger. I made some edits and also suggested some introductory text—all in the document you linked. See what you think.

**Comment by semioticrobotic** [comment]
I'd like to publish on March 28. @LauraHilliger, do you think we can hit that mark?

**Comment by LauraHilliger** [comment]
Yessir! #OnIt

**Comment by LauraHilliger** [comment]
Wrote and rewrote, the ending is a bit abrupt maybe?

**Comment by semioticrobotic** [comment]
Solid edits and great work, @LauraHilliger. I have made just a few adjustments and posed one or two final questions for you (I hope addressing them will be relatively straightforward for you). When you've seen this once more, I'm happy to typeset it for final review.

**Comment by LauraHilliger** [comment]
made some small edits, but I'm done if you think it's good!!

**Comment by semioticrobotic** [comment]
If you're good, then I'm good (and I think it looks great!).

**Comment by semioticrobotic** [comment]
Alright! This is scheduled to appear on March 28 as ["Why do organizations have open secrets?"](https://opensource.com/open-organization/19/3/open-secrets-bystander-effect) Great work, @LauraHilliger.

**Comment by semioticrobotic** [comment]
Published! Thanks for taking this on (and crushing it), @LauraHilliger!
