### ISSUE TITLE
Simplifying organizational change: A guide for the perplexed

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#49]
New guide from @jenkelchner:

> Most of us have encountered a certain paralysis around implementing culture change because of the perceived difficulty and time to realize our efforts. However, change is as hard as we choose to make it. In order to win at change, we must simplify our understanding and approach.

**Comment by semioticrobotic** [comment]
How does April 18 strike you as a potential publication date, @jenkelchner?

**Comment by jenkelchner** [comment]
@semioticrobotic let's do it 👍

**Comment by jenkelchner** [comment]
@semioticrobotic - proof reviewed and accepted.  Please add the repository link with some sort of CTA.  I will continue to build out an ebook and visuals I'll add to this https://github.com/jenkelchner/simplifying-change

**Comment by semioticrobotic** [comment]
Sounds great, @jenkelchner. I added an in-text CtA directing readers to the visual guide itself, and then, at the end of the article, a more general CtA that takes folks directly to [your repo](https://github.com/jenkelchner/simplifying-change). If you refresh your proofs you should see them both.

**Comment by jenkelchner** [comment]
@semioticrobotic looks fantabulous.  Thank you!!

**Comment by semioticrobotic** [comment]
Excellent! This puppy is _on the calendar_ for April 18!

**Comment by semioticrobotic** [comment]
Published!
