### ISSUE TITLE
Resilient versus reactive organizations

### ISSUE THREAD

**Issue by funnelfiasco** [open-organization-ambassadors/ambassador-board-room#50]
This took a different path than I had originally discussed in email with you @semioticrobotic, but you'll get that sometimes.

https://docs.google.com/document/d/1R0UUBz2tJtnzA5MDyOOgADafopyGNvn68IaZWtX3FYA/edit?usp=sharing

**Comment by semioticrobotic** [comment]
Thanks, @funnelfiasco! I'm on it.

**Comment by semioticrobotic** [comment]
Great first draft, @funnelfiasco. I made some comments for your consideration.

By the way, have you read or studied the work of Niklas Luhmann? What you've written here resonates with his systems-theoretical approach to organizational dynamics.

**Comment by funnelfiasco** [comment]
I have not, but I've added to the reading list. I like your edits and have made another pass at the closer.

**Comment by semioticrobotic** [comment]
Looking great. Back at you.

**Comment by funnelfiasco** [comment]
I like your suggestion. Shipit!

**Comment by semioticrobotic** [comment]
This is typeset and [ready for your review](https://opensource.com/open-organization/19/4/resilient-v-reactive-organizations), @funnelfiasco. I'm having a bad headline-brainstorming day. What do you think of options like these?

- Will your organization change itself to death? (working title)
- Striving for organizational resilience
- How flexible is too flexible for your open organization?
- Your team should strive for resilience, not just reaction
- Adaptability has its limits

**Comment by funnelfiasco** [comment]
LGTM. I like the working title!

**Comment by semioticrobotic** [comment]
Then the working title ye shall have! Scheduled to run, with that headline, on April 23.

Awesome job, @funnelfiasco. So glad you've joined us here.

**Comment by semioticrobotic** [comment]
Published!
