### ISSUE TITLE
publish advice on using an issue tracker

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#9]
- [**Working Draft**](https://docs.google.com/document/d/11PJqRuFfWutwgLiwIXa6d99wUJWwJ-E_bRMx-S8jsEY/edit)
- [Draft 1](https://docs.google.com/document/d/17WvNWbmRlgNhnBYy4lL-cxs_lLN46u88ipICTB1v_is/edit?usp=sharing)

**Comment by whit537** [comment]
@semioticrobotic Soooo the handbooks piece (#7) is turning out to be a fair bit of work, in that I will need to read a bunch of handbooks! :-P

Therefore, I started a [draft](https://docs.google.com/document/d/11PJqRuFfWutwgLiwIXa6d99wUJWwJ-E_bRMx-S8jsEY/edit) of a different piece on the bus this morning, about how to effectively use an issue tracker in an open organization—something easier for me to write, as well as something germane to our conversation next Tuesday. ;-)

Hopefully we can get this into the pipeline for publishing in February?

**Comment by semioticrobotic** [comment]
That sounds like a great idea. I'll have a look soon. And of course you know you can always send questions or requests for review my way.

**Comment by semioticrobotic** [comment]
Shaping up nicely! I just made a few comments on it. Always appreciate the opportunity to offer advice at an early stage, while pieces are still protean. Thanks, @whit537! This will be such a nice resource.

**Comment by whit537** [comment]
Thanks for the helpful comments, @semioticrobotic! Good eye for keeping it accessible to less technical folks.

**Comment by whit537** [comment]
Okay! @semioticrobotic Just wrapped up a [first draft](https://docs.google.com/document/d/11PJqRuFfWutwgLiwIXa6d99wUJWwJ-E_bRMx-S8jsEY/edit) for this piece. Take a look and let me know how it reads to you.

**Comment by semioticrobotic** [comment]
Really like this, @whit537. It's such a valuable resource and I'm excited to publish it. I made a few suggestions in the document, none of which are major or represent blockers to publication. Have a look, and when you confirm a final draft, I will go ahead and put it into production for February.

**Comment by whit537** [comment]
All set to proceed, @semioticrobotic. I'm fine with your edits. 👍

Let me know when we have a page proof and/or what else you need from me!

**Comment by semioticrobotic** [comment]
Very good, @whit537. I will go ahead and put it into production.

**Comment by whit537** [comment]
Thanks for queueing up the post, @semioticrobotic. I've made a few light edits, which I believe you can [view here](https://opensource.com/node/34206/revisions/view/223486/223571). If anything looks questionable, let me know!

Regarding the headline: once it settles, how hard should we try to sync that up with the URL slug of the piece?

Looking forward to seeing this out there!

**Comment by semioticrobotic** [comment]
All looks great, @whit537. Thanks for your work on this. So good.

Yes, we can definitely sync the slug at the time of publication!

**Comment by whit537** [comment]
Copy that, gold leader. 🚀

**Comment by whit537** [comment]
We're live! 💃 

https://opensource.com/open-organization/17/2/tracking-issues-publicly
